#ifndef OBJECTSTATICS_H
#define OBJECTSTATICS_H

// NOTE: AUTO-GENERATED BY generateStatics.py

#include <string>
#include <iostream>
#include "Object.h"
#include "Shape.h"

#define DEBUGGING true

class ObjectStaticsClass
{
    public:
    static Material* createMaterial( std::string materialKey )
    {
        Material* returnMaterial;
        if( materialKey == "SLINGSHOT" ) {
            returnMaterial = new Material( '1', -1, 10000, 0.05, 0.05, 10000 );
        } else if( materialKey == "BIRD_RED" ) {
            returnMaterial = new Material( '0', 1, 6, 0.3, 0.43, 2 );
        } else if( materialKey == "BIRD_YELLOW" ) {
            returnMaterial = new Material( '0', 1, 6, 0.3, 0.23, 2 );
        } else if( materialKey == "BIRD_BLUE" ) {
            returnMaterial = new Material( '0', 1, 4.5, 0.3, 0.25, 2 );
        } else if( materialKey == "BIRD_WHITE" ) {
            returnMaterial = new Material( '0', 1.0, 4.0, 0.3, 0.23, 2 );
        } else if( materialKey == "BIRD_BLACK" ) {
            returnMaterial = new Material( '0', 1.0, 6.0, 0.3, 0.03, 2 );
        } else if( materialKey == "BIRD_GREEN" ) {
            returnMaterial = new Material( '0', 1, 7, 0.2, 0.4, 2 );
        } else if( materialKey == "BIRD_REDBIG" ) {
            returnMaterial = new Material( '0', 1, 8, 0.3, 0.4, 2 );
        } else if( materialKey == "PIG_BASIC_SMALL" ) {
            returnMaterial = new Material( '0', 1, 2, 0.7, 0.05, 4 );
        } else if( materialKey == "PIG_BASIC_MEDIUM" ) {
            returnMaterial = new Material( '0', 1, 2, 0.3, 0.05, 10 );
        } else if( materialKey == "PIG_BASIC_BIG" ) {
            returnMaterial = new Material( '0', 1, 2, 0.3, 0.05, 20 );
        } else if( materialKey == "PIG_KING" ) {
            returnMaterial = new Material( '0', 0, 1, 0.3, 0.05, 100 );
        } else if( materialKey == "PIG_MUSTACHE" ) {
            returnMaterial = new Material( '0', 1, 1, 0.3, 0.05, 30 );
        } else if( materialKey == "PIG_HELMET" ) {
            returnMaterial = new Material( '0', 8, 2, 0.3, 0.05, 15 );
        } else if( materialKey == "BLOCK_WOOD" ) {
            returnMaterial = new Material( '0', 2.5, 1.5, 4, 0.0, 15 );
        } else if( materialKey == "BLOCK_SNOW" ) {
            returnMaterial = new Material( '0', 10, 2, 4.5, 0.0, 15 );
        } else if( materialKey == "BLOCK_SNOW_STATIC" ) {
            returnMaterial = new Material( '1', 6, 1, 1, 0.2, 8 );
        } else if( materialKey == "BLOCK_ICE" ) {
            returnMaterial = new Material( '0', 2, 0.75, 0.7, 0.2, 8 );
        } else if( materialKey == "BLOCK_STONE" ) {
            returnMaterial = new Material( '0', 15, 4, 4, 0.1, 25 );
        } else if( materialKey == "GROUND_HILLS" ) {
            returnMaterial = new Material( '1', -1, 0.5, 0.8, 0.0, 100 );
        } else if( materialKey == "TEXTURE_HILLS" ) {
            returnMaterial = new Material( '1', -1, 0.5, 0.8, 0.0, 100 );
        } else if( materialKey == "ESTRADE" ) {
            returnMaterial = new Material( '1', -1, 0.5, 0.7, 0.05, 100 );
        } else if( materialKey == "GROUND_SNOW" ) {
            returnMaterial = new Material( '1', -1, 0.5, 0.7, 0.05, 100  );
        } else {
            returnMaterial = new Material( '0', 0, 0, 0, 0, 0 );
        }

        if( DEBUGGING ) {
            std::cout << "Material: " + materialKey << std::endl; 
        }

        return returnMaterial;
    }

    static Shape* createShape( std::string shapeKey )
    {
        Shape* returnShape;

        if( shapeKey == "PROP_HAT_BANDITO" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "B_SUSHI" ) {
            returnShape = new RectangleShape( 48.0, 56.0 );
        } else if( shapeKey == "EASTER_CLOVERWOOD" ) {
            returnShape = new RectangleShape( 83.0, 41.0 );
        } else if( shapeKey == "BLOCK_RECT_5X5_STATIC" ) {
            returnShape = new RectangleShape( 97.0, 97.0 );
        } else if( shapeKey == "MISC_METAL_PILLAR" ) {
            returnShape = new RectangleShape( 81.88, 181.24 );
        } else if( shapeKey == "MISC_METAL_BALL" ) {
            returnShape = new CircleShape( 16.56, 0.0, 0.0 );
        } else if( shapeKey == "BIRD_RECT_SARDINE" ) {
            returnShape = new RectangleShape( 64.4, 41.4 );
        } else if( shapeKey == "PIG_CIRCLE_SMALL" ) {
            returnShape = new CircleShape( 21.5, 0.0, 0.0 );
        } else if( shapeKey == "BIRD_CIRCLE_BLUE" ) {
            returnShape = new CircleShape( 12.0, 2.0, 3.0 );
        } else if( shapeKey == "BLOCK_RECT_10X1" ) {
            returnShape = new RectangleShape( 188.6, 18.4 );
        } else if( shapeKey == "PIG_CIRCLE_BIG" ) {
            returnShape = new CircleShape( 46.5, 0.0, 0.0 );
        } else if( shapeKey == "BLOCK_CIRCLE_3X3" ) {
            returnShape = new CircleShape( 28.0, 0.0, 0.0 );
        } else if( shapeKey == "PIG_CIRCLE_HELMET" ) {
            returnShape = new CircleShape( 39.0, 0.0, 0.0 );
        } else if( shapeKey == "EASTER_WHITE_BUNNY_NOSE_1" ) {
            returnShape = new RectangleShape( 38.0, 37.0 );
        } else if( shapeKey == "BIRD_CIRCLE_YELLOW" ) {
            returnShape = new CircleShape( 16.0, 7.0, 8.0 );
        } else if( shapeKey == "MISC_ESTRADE_9X3" ) {
            returnShape = new RectangleShape( 177.0, 54.0 );
        } else if( shapeKey == "BIRD_CIRCLE_GREEN" ) {
            returnShape = new CircleShape( 20.0, -12.0, 6.0 );
        } else if( shapeKey == "PROP_HELMET_BIG" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "MISC_HAT_ELF_9X5" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "BLOCK_FUJITV_BALL" ) {
            returnShape = new CircleShape( 60.0, 0.0, 0.0 );
        } else if( shapeKey == "PROP_ROPE_THIN" ) {
            returnShape = new RectangleShape( 3.68, 120.52 );
        } else if( shapeKey == "BLOCK_RECT_4X4" ) {
            returnShape = new RectangleShape( 75.44, 75.44 );
        } else if( shapeKey == "BLOCK_RECT_4X2" ) {
            returnShape = new RectangleShape( 76.36, 37.72 );
        } else if( shapeKey == "BLOCK_RECT_4X1" ) {
            returnShape = new RectangleShape( 76.36, 18.4 );
        } else if( shapeKey == "MISC_METAL_TIRE_4X4" ) {
            returnShape = new CircleShape( 34.96, 0.0, 0.0 );
        } else if( shapeKey == "MISC_METAL_CHEST" ) {
            returnShape = new RectangleShape( 90.0, 58.8 );
        } else if( shapeKey == "BLOCK_RECT_1X1" ) {
            returnShape = new RectangleShape( 18.4, 18.4 );
        } else if( shapeKey == "BLOCK_RECT_10X10_STATIC" ) {
            returnShape = new RectangleShape( 194.0, 196.0 );
        } else if( shapeKey == "MISC_METAL_HOLYGRAIL" ) {
            returnShape = new RectangleShape( 40.0, 80.0 );
        } else if( shapeKey == "MISC_FOOD_CIRCLE_APPLE" ) {
            returnShape = new CircleShape( 23.92, 0.0, -2.0 );
        } else if( shapeKey == "PROP_HELMET_SMALL" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "MISC_RUBBER_DICE" ) {
            returnShape = new RectangleShape( 57.0, 57.0 );
        } else if( shapeKey == "BLOCK_RECT_10X2_STATIC" ) {
            returnShape = new RectangleShape( 194.0, 33.0 );
        } else if( shapeKey == "PROP_CARPET" ) {
            returnShape = new RectangleShape( 256.68, 70.84 );
        } else if( shapeKey == "PROP_HAT_SHERIFF" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "MISC_FOOD_POLYGON_STRAWBERRY" ) {
            returnShape = new CircleShape( 24.84, 0.0, -2.0 );
        } else if( shapeKey == "MISC_PIG_WEIGHT" ) {
            returnShape = new RectangleShape( 50.72, 30.72 );
        } else if( shapeKey == "EASTER_BLOCK_STATIC_CLOUD_2" ) {
            returnShape = new RectangleShape( 82.0, 38.0 );
        } else if( shapeKey == "B_RICEBALL" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "BLOCK_TRIANGLE_4X4_EQUILATERAL" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "MISC_METAL_FLAG" ) {
            returnShape = new RectangleShape( 44.0, 116.0 );
        } else if( shapeKey == "MISC_METAL_TNT" ) {
            returnShape = new RectangleShape( 64.4, 63.48 );
        } else if( shapeKey == "BLOCK_FUJITV_DOG2" ) {
            returnShape = new RectangleShape( 120.0, 68.0 );
        } else if( shapeKey == "BIRD_POLYGON_MIGHTY_EAGLE" ) {
            returnShape = new CircleShape( 110.0, 0.0, 0.0 );
        } else if( shapeKey == "EASTER_FOURLEAF_CLOVER" ) {
            returnShape = new RectangleShape( 115.0, 82.0 );
        } else if( shapeKey == "MISC_HAT_ELF_6X3" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "B_CANDYSTICK" ) {
            returnShape = new RectangleShape( 18.0, 65.0 );
        } else if( shapeKey == "MISC_FOOD_CIRCLE_DONUT" ) {
            returnShape = new CircleShape( 28.52, 0.0, 0.0 );
        } else if( shapeKey == "B_SAKURAFLOWER_PETAL" ) {
            returnShape = new RectangleShape( 18.0, 29.0 );
        } else if( shapeKey == "MISC_HELMET_SMALL" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "EASTER_WHITE_BUNNY_EAR_1" ) {
            returnShape = new RectangleShape( 20.0, 30.0 );
        } else if( shapeKey == "PIG_CIRCLE_MUSTACHE" ) {
            returnShape = new CircleShape( 44.0, 0.0, 0.0 );
        } else if( shapeKey == "BIRD_CIRCLE_BLACK" ) {
            returnShape = new CircleShape( 20.0, 3.0, 15.0 );
        } else if( shapeKey == "BLOCK_CIRCLE_4X4" ) {
            returnShape = new CircleShape( 36.0, 0.0, 0.0 );
        } else if( shapeKey == "MISC_METAL_TOILET" ) {
            returnShape = new RectangleShape( 60.0, 90.0 );
        } else if( shapeKey == "BLOCK_TRIANGLE_4X4_LEFT" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "EASTER_BLOCK_STATIC_CLOUD_1" ) {
            returnShape = new RectangleShape( 41.0, 38.0 );
        } else if( shapeKey == "BLOCK_RECT_8X1" ) {
            returnShape = new RectangleShape( 154.56, 18.4 );
        } else if( shapeKey == "BIRD_CIRCLE_RED" ) {
            returnShape = new CircleShape( 17.0, 5.0, 7.0 );
        } else if( shapeKey == "EASTER_BLOCK_STATIC_CLOUD_4" ) {
            returnShape = new RectangleShape( 167.0, 86.0 );
        } else if( shapeKey == "MISC_FOOD_POLYGON_HAM" ) {
            returnShape = new CircleShape( 32.2, 0.0, -2.0 );
        } else if( shapeKey == "MISC_RUBBER_DUCK" ) {
            returnShape = new CircleShape( 33.0, 0.0, 5.0 );
        } else if( shapeKey == "BLOCK_TRIANGLE_2X2_RIGHT" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "MISC_HAT_ELF_3X2" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "B_JAPANESE_UMBRELLA" ) {
            returnShape = new RectangleShape( 50.0, 109.0 );
        } else if( shapeKey == "EASTER_WHITE_BUNNY_EAR_2" ) {
            returnShape = new RectangleShape( 26.0, 25.0 );
        } else if( shapeKey == "PROP_HAT_COWBOY_BIG" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "PROP_ROPE_THICK" ) {
            returnShape = new RectangleShape( 10.12, 121.44 );
        } else if( shapeKey == "EASTER_BLOCK_COMBINE" ) {
            returnShape = new RectangleShape( 53.0, 14.0 );
        } else if( shapeKey == "B_SAKURAFLOWER_CENTER" ) {
            returnShape = new RectangleShape( 25.0, 22.0 );
        } else if( shapeKey == "MISC_METAL_TIRE_3X3" ) {
            returnShape = new CircleShape( 29.44, 0.0, 0.0 );
        } else if( shapeKey == "MISC_HELMET_BOSS" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "MISC_BALLOON_PIG" ) {
            returnShape = new RectangleShape( 73.6, 110.4 );
        } else if( shapeKey == "MISC_GIFT_4X5" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "SLINGSHOT" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "BLOCK_CIRCLE_2X2" ) {
            returnShape = new CircleShape( 20.0, 0.0, 0.0 );
        } else if( shapeKey == "GROUND" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "MISC_ESTRADE_11X3" ) {
            returnShape = new RectangleShape( 223.0, 63.0 );
        } else if( shapeKey == "MISC_METAL_TIRE_2X2" ) {
            returnShape = new CircleShape( 23.92, 0.0, 0.0 );
        } else if( shapeKey == "EASTER_GRASS_2" ) {
            returnShape = new RectangleShape( 50.0, 15.0 );
        } else if( shapeKey == "EASTER_GRASS_1" ) {
            returnShape = new RectangleShape( 50.0, 15.0 );
        } else if( shapeKey == "B_SUSHICHEF_BANDANNA" ) {
            returnShape = new RectangleShape( 68.0, 18.0 );
        } else if( shapeKey == "MISC_HAT_WINTER_4X3" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "MISC_BEACHBALL" ) {
            returnShape = new CircleShape( 37.0, 0.0, 0.0 );
        } else if( shapeKey == "MISC_METAL_CHAIN" ) {
            returnShape = new RectangleShape( 18.4, 73.6 );
        } else if( shapeKey == "MISC_GIFT_7X4" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "PIG_CIRCLE_MEDIUM" ) {
            returnShape = new CircleShape( 37.0, 0.0, 0.0 );
        } else if( shapeKey == "MISC_HELMET_BIG" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "PIG_CIRCLE_KING" ) {
            returnShape = new CircleShape( 56.5, 0.0, 16.0 );
        } else if( shapeKey == "BLOCK_RECT_6X2" ) {
            returnShape = new RectangleShape( 111.32, 37.72 );
        } else if( shapeKey == "MISC_ESTRADE_1X2" ) {
            returnShape = new RectangleShape( 17.0, 27.0 );
        } else if( shapeKey == "MISC_KING_BEARD_7X4" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "BIRD_CIRCLE_WHITE" ) {
            returnShape = new CircleShape( 26.0, 9.0, 16.0 );
        } else if( shapeKey == "B_MISO" ) {
            returnShape = new RectangleShape( 57.0, 54.0 );
        } else if( shapeKey == "MISC_RUBBER_SMILEY" ) {
            returnShape = new CircleShape( 36.0, 0.0, 0.0 );
        } else if( shapeKey == "EASTER_PINK_BUNNY_HAT_1" ) {
            returnShape = new RectangleShape( 30.0, 13.0 );
        } else if( shapeKey == "MISC_ESTRADE_2X2" ) {
            returnShape = new RectangleShape( 45.0, 40.0 );
        } else if( shapeKey == "EASTER_BLOCK_STATIC_CLOUD_3" ) {
            returnShape = new RectangleShape( 84.0, 79.0 );
        } else if( shapeKey == "EASTER_EASTEREGG" ) {
            returnShape = new CircleShape( 25.0, 0.0, 0.0 );
        } else if( shapeKey == "MISC_BALLOON_NORMAL" ) {
            returnShape = new RectangleShape( 48.76, 66.24 );
        } else if( shapeKey == "MISC_ESTRADE_7X2" ) {
            returnShape = new RectangleShape( 147.0, 42.0 );
        } else if( shapeKey == "EASTER_PINK_BUNNY_HAT_2" ) {
            returnShape = new RectangleShape( 30.0, 10.0 );
        } else if( shapeKey == "MISC_GIFT_6X3" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "BLOCK_RECT_32X2_STATIC" ) {
            returnShape = new RectangleShape( 642.0, 33.0 );
        } else if( shapeKey == "BLOCK_RECT_2X1" ) {
            returnShape = new RectangleShape( 37.72, 18.4 );
        } else if( shapeKey == "BLOCK_RECT_2X2" ) {
            returnShape = new RectangleShape( 37.72, 37.72 );
        } else if( shapeKey == "MISC_FOOD_CIRCLE_WATERMELON" ) {
            returnShape = new CircleShape( 32.66, 0.0, 0.0 );
        } else if( shapeKey == "EASTER_KING_BUNNY_HAT_1" ) {
            returnShape = new RectangleShape( 140.0, 150.0 );
        } else if( shapeKey == "EASTER_SPECIAL_EASTEREGG" ) {
            returnShape = new RectangleShape( 45.0, 82.0 );
        } else if( shapeKey == "BLOCK_RECT_3X3" ) {
            returnShape = new RectangleShape( 56.0, 56.0 );
        } else if( shapeKey == "BIRD_CIRCLE_REDBIG" ) {
            returnShape = new CircleShape( 36.0, 9.0, 9.0 );
        } else if( shapeKey == "BLOCK_RECT_1X1_STATIC" ) {
            returnShape = new RectangleShape( 18.4, 18.4 );
        } else if( shapeKey == "BLOCK_TRIANGLE_4X4_RIGHT" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "BLOCK_RECT_5X2_STATIC" ) {
            returnShape = new RectangleShape( 97.0, 32.0 );
        } else if( shapeKey == "MISC_FOOD_CIRCLE_EGG" ) {
            returnShape = new CircleShape( 20.7, 0.0, 4.0 );
        } else if( shapeKey == "MISC_METAL_DIAMOND" ) {
            returnShape = new PolygonShape(   );
        } else if( shapeKey == "MISC_FOOD_POLYGON_BANANA" ) {
            returnShape = new RectangleShape( 73.6, 40.48 );
        } else if( shapeKey == "PROP_ROPE_THIN_SHORT" ) {
            returnShape = new RectangleShape( 3.68, 59.8 );
        } else if( shapeKey == "MISC_RUBBER_TRAMPOLINE" ) {
            returnShape = new RectangleShape( 138.0, 27.6 );
        } else if( shapeKey == "PROP_HAT_COWBOY_SMALL" ) {
            returnShape = new PolygonShape(   );
        }
        if( DEBUGGING ) {
            std::cout << "Shape: " + shapeKey << std::endl; 
        }

        return returnShape;
    }

    static Object* createObject( std::string objectKey )
    {
        Object* returnObject;
        if( objectKey == "SLINGSHOT" ) {
            returnObject = new Object( "SLINGSHOT", createMaterial( "SLINGSHOT" ), createShape( "SLINGSHOT" ), 0, "SLINGSHOT" );
        } else if( objectKey == "BIRD_RED" ) {
            returnObject = new Bird( "BIRD", createMaterial( "BIRD_RED" ), createShape( "BIRD_CIRCLE_RED" ), 100, "BIRD_GROUP", 2, 2 );
        } else if( objectKey == "BIRD_YELLOW" ) {
            returnObject = new Bird( "BIRD", createMaterial( "BIRD_YELLOW" ), createShape( "BIRD_CIRCLE_YELLOW" ), 100, "BIRD_GROUP", 2, 2 );
        } else if( objectKey == "BIRD_BLUE" ) {
            returnObject = new Bird( "BIRD", createMaterial( "BIRD_BLUE" ), createShape( "BIRD_CIRCLE_BLUE" ), 100, "BIRD_GROUP", 2, 2 );
        } else if( objectKey == "BIRD_WHITE" ) {
            returnObject = new Bird( "BIRD", createMaterial( "BIRD_WHITE" ), createShape( "BIRD_CIRCLE_WHITE" ), 100, "BIRD_GROUP", 2, 2 );
        } else if( objectKey == "BIRD_BLACK" ) {
            returnObject = new Bird( "BIRD", createMaterial( "BIRD_BLACK" ), createShape( "BIRD_CIRCLE_BLACK" ), 100, "BIRD_GROUP", 1, 2 );
        } else if( objectKey == "BIRD_GREEN" ) {
            returnObject = new Bird( "BIRD", createMaterial( "BIRD_GREEN" ), createShape( "BIRD_CIRCLE_GREEN" ), 100, "BIRD_GROUP", 2, -1 );
        } else if( objectKey == "BIRD_REDBIG" ) {
            returnObject = new Bird( "BIRD", createMaterial( "BIRD_REDBIG" ), createShape( "BIRD_CIRCLE_REDBIG" ), 100, "BIRD_GROUP", 1, -1 );
        } else if( objectKey == "PIG_BASIC_SMALL" ) {
            returnObject = new Pig( "PIG", createMaterial( "PIG_BASIC_SMALL" ), createShape( "PIG_CIRCLE_SMALL" ), 5000, "PIG_GROUP", 4 );
        } else if( objectKey == "PIG_BASIC_MEDIUM" ) {
            returnObject = new Pig( "PIG", createMaterial( "PIG_BASIC_MEDIUM" ), createShape( "PIG_CIRCLE_MEDIUM" ), 5000, "PIG_GROUP", 10 );
        } else if( objectKey == "PIG_BASIC_BIG" ) {
            returnObject = new Pig( "PIG", createMaterial( "PIG_BASIC_BIG" ), createShape( "PIG_CIRCLE_BIG" ), 5000, "PIG_GROUP", 20 );
        } else if( objectKey == "PIG_KING" ) {
            returnObject = new Pig( "PIG", createMaterial( "PIG_KING" ), createShape( "PIG_CIRCLE_KING" ), 5000, "PIG_GROUP", 100 );
        } else if( objectKey == "PIG_MUSTACHE" ) {
            returnObject = new Pig( "PIG", createMaterial( "PIG_MUSTACHE" ), createShape( "PIG_CIRCLE_MUSTACHE" ), 5000, "PIG_GROUP", 30 );
        } else if( objectKey == "PIG_HELMET" ) {
            returnObject = new Pig( "PIG", createMaterial( "PIG_HELMET" ), createShape( "PIG_CIRCLE_HELMET" ), 5000, "PIG_GROUP", 15 );
        } else if( objectKey == "GROUND_HILLS" ) {
            returnObject = new Object( "GROUND", createMaterial( "GROUND_HILLS" ), createShape( "GROUND" ), 0, "NO_GROUP" );
        } else if( objectKey == "GROUND_SNOW" ) {
            returnObject = new Object( "GROUND", createMaterial( "GROUND_SNOW" ), createShape( "GROUND" ), 0, "NO_GROUP" );
        } else if( objectKey == "TERRAIN_TEXTURED_HILLS_1X1" ) {
            returnObject = new Terrain( "BLOCK_STATIC", createMaterial( "TEXTURE_HILLS" ), createShape( "BLOCK_RECT_1X1_STATIC" ), 0, "STATIC_GROUP", 1 );
        } else if( objectKey == "TERRAIN_TEXTURED_HILLS_5X2" ) {
            returnObject = new Terrain( "BLOCK_STATIC", createMaterial( "TEXTURE_HILLS" ), createShape( "BLOCK_RECT_5X2_STATIC" ), 0, "STATIC_GROUP", 1 );
        } else if( objectKey == "TERRAIN_TEXTURED_HILLS_5X5" ) {
            returnObject = new Terrain( "BLOCK_STATIC", createMaterial( "TEXTURE_HILLS" ), createShape( "BLOCK_RECT_5X5_STATIC" ), 0, "STATIC_GROUP", 1 );
        } else if( objectKey == "TERRAIN_TEXTURED_HILLS_10X2" ) {
            returnObject = new Terrain( "BLOCK_STATIC", createMaterial( "TEXTURE_HILLS" ), createShape( "BLOCK_RECT_10X2_STATIC" ), 0, "STATIC_GROUP", 1 );
        } else if( objectKey == "TERRAIN_TEXTURED_HILLS_10X10" ) {
            returnObject = new Terrain( "BLOCK_STATIC", createMaterial( "TEXTURE_HILLS" ), createShape( "BLOCK_RECT_10X10_STATIC" ), 0, "STATIC_GROUP", 1 );
        } else if( objectKey == "TERRAIN_TEXTURED_HILLS_32X2" ) {
            returnObject = new Terrain( "BLOCK_STATIC", createMaterial( "TEXTURE_HILLS" ), createShape( "BLOCK_RECT_32X2_STATIC" ), 0, "STATIC_GROUP", 1 );
        } else if( objectKey == "MISC_ESTRADE_7X2" ) {
            returnObject = new Terrain( "BLOCK_MISC", createMaterial( "ESTRADE" ), createShape( "MISC_ESTRADE_7X2" ), 0, "ESTRADE_GROUP", 1 );
        } else if( objectKey == "MISC_ESTRADE_9X3" ) {
            returnObject = new Terrain( "BLOCK_MISC", createMaterial( "ESTRADE" ), createShape( "MISC_ESTRADE_9X3" ), 0, "ESTRADE_GROUP", 1 );
        } else if( objectKey == "MISC_ESTRADE_11X3" ) {
            returnObject = new Terrain( "BLOCK_MISC", createMaterial( "ESTRADE" ), createShape( "MISC_ESTRADE_11X3" ), 0, "ESTRADE_GROUP", 1 );
        } else if( objectKey == "MISC_ESTRADE_1X2" ) {
            returnObject = new Terrain( "BLOCK_MISC", createMaterial( "ESTRADE" ), createShape( "MISC_ESTRADE_1X2" ), 0, "TRASH_GROUP", 1 );
        } else if( objectKey == "MISC_ESTRADE_2X2" ) {
            returnObject = new Terrain( "BLOCK_MISC", createMaterial( "BLOCK_WOOD" ), createShape( "MISC_ESTRADE_2X2" ), 500, "TRASH_GROUP", 1 );
        } else if( objectKey == "WOOD_BLOCK_1X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_RECT_1X1" ), 500, "WOOD_GROUP", 20 );
        } else if( objectKey == "WOOD_BLOCK_2X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_RECT_2X1" ), 500, "WOOD_GROUP", 40 );
        } else if( objectKey == "WOOD_BLOCK_2X2" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_RECT_2X2" ), 500, "WOOD_GROUP", 60 );
        } else if( objectKey == "WOOD_BLOCK_4X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_RECT_4X1" ), 500, "WOOD_GROUP", 50 );
        } else if( objectKey == "WOOD_BLOCK_4X2" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_RECT_4X2" ), 500, "WOOD_GROUP", 80 );
        } else if( objectKey == "WOOD_BLOCK_4X4_HOLLOW" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_RECT_4X4" ), 500, "WOOD_GROUP", 120 );
        } else if( objectKey == "WOOD_BLOCK_8X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_RECT_8X1" ), 500, "WOOD_GROUP", 70 );
        } else if( objectKey == "WOOD_BLOCK_10X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_RECT_10X1" ), 500, "WOOD_GROUP", 100 );
        } else if( objectKey == "WOOD_CIRCLE_2X2" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_CIRCLE_2X2" ), 500, "WOOD_GROUP", 150 );
        } else if( objectKey == "WOOD_CIRCLE_4X4" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_CIRCLE_4X4" ), 500, "WOOD_GROUP", 200 );
        } else if( objectKey == "WOOD_TRIANGLE_4X4" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_TRIANGLE_4X4_LEFT" ), 500, "WOOD_GROUP", 80 );
        } else if( objectKey == "WOOD_TRIANGLE_4X4_HOLLOW" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_WOOD" ), createShape( "BLOCK_TRIANGLE_4X4_EQUILATERAL" ), 500, "WOOD_GROUP", 70 );
        } else if( objectKey == "STONE_BLOCK_1X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_RECT_1X1" ), 500, "STONE_GROUP", 30 );
        } else if( objectKey == "STONE_BLOCK_2X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_RECT_2X1" ), 500, "STONE_GROUP", 60 );
        } else if( objectKey == "STONE_BLOCK_2X2" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_RECT_2X2" ), 500, "STONE_GROUP", 100 );
        } else if( objectKey == "STONE_BLOCK_4X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_RECT_4X1" ), 500, "STONE_GROUP", 80 );
        } else if( objectKey == "STONE_BLOCK_4X2" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_RECT_4X2" ), 500, "STONE_GROUP", 140 );
        } else if( objectKey == "STONE_BLOCK_4X4_HOLLOW" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_RECT_4X4" ), 500, "STONE_GROUP", 160 );
        } else if( objectKey == "STONE_BLOCK_8X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_RECT_8X1" ), 500, "STONE_GROUP", 120 );
        } else if( objectKey == "STONE_BLOCK_10X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_RECT_10X1" ), 500, "STONE_GROUP", 140 );
        } else if( objectKey == "STONE_CIRCLE_2X2" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_CIRCLE_2X2" ), 500, "STONE_GROUP", 300 );
        } else if( objectKey == "STONE_CIRCLE_4X4" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_CIRCLE_4X4" ), 500, "STONE_GROUP", 600 );
        } else if( objectKey == "STONE_TRIANGLE_4X4" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_TRIANGLE_4X4_LEFT" ), 500, "STONE_GROUP", 140 );
        } else if( objectKey == "STONE_TRIANGLE_4X4_HOLLOW" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_STONE" ), createShape( "BLOCK_TRIANGLE_4X4_EQUILATERAL" ), 500, "STONE_GROUP", 140 );
        } else if( objectKey == "ICE_BLOCK_1X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_RECT_1X1" ), 500, "ICE_GROUP", 13 );
        } else if( objectKey == "ICE_BLOCK_2X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_RECT_2X1" ), 500, "ICE_GROUP", 26 );
        } else if( objectKey == "ICE_BLOCK_2X2" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_RECT_2X2" ), 500, "ICE_GROUP", 40 );
        } else if( objectKey == "ICE_BLOCK_4X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_RECT_4X1" ), 500, "ICE_GROUP", 33 );
        } else if( objectKey == "ICE_BLOCK_4X2" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_RECT_4X2" ), 500, "ICE_GROUP", 53 );
        } else if( objectKey == "ICE_BLOCK_4X4_HOLLOW" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_RECT_4X4" ), 500, "ICE_GROUP", 70 );
        } else if( objectKey == "ICE_BLOCK_8X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_RECT_8X1" ), 500, "ICE_GROUP", 47 );
        } else if( objectKey == "ICE_BLOCK_10X1" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_RECT_10X1" ), 500, "ICE_GROUP", 65 );
        } else if( objectKey == "ICE_CIRCLE_2X2" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_CIRCLE_2X2" ), 500, "ICE_GROUP", 100 );
        } else if( objectKey == "ICE_CIRCLE_4X4" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_CIRCLE_4X4" ), 500, "ICE_GROUP", 125 );
        } else if( objectKey == "ICE_TRIANGLE_4X4" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_TRIANGLE_4X4_LEFT" ), 500, "ICE_GROUP", 53 );
        } else if( objectKey == "ICE_TRIANGLE_4X4_HOLLOW" ) {
            returnObject = new Block( "BLOCK_BASIC", createMaterial( "BLOCK_ICE" ), createShape( "BLOCK_TRIANGLE_4X4_EQUILATERAL" ), 500, "ICE_GROUP", 48  );
        } else {
			returnObject = new Object( "SLINGSHOT", createMaterial( "SLINGSHOT" ), createShape( "SLINGSHOT" ), 0, "SLINGSHOT" );
        }

        if( DEBUGGING ) {
            std::cout << "Object: " + objectKey << std::endl; 
        }

        return returnObject;
    }
};

#endif